name=input("Enter your name: ")
age=int(input("Enter your age: "))
height=float(input("Enter your height in meters: "))
fav=input("Enter your favorite programming language: ")
print("----PROFILE SUMMARY-----")
print("Name: ",name)
print("Next year you will be ",age+1,)
print("Your height in cm is",height*100,"cm")
print("You love programming in ",fav)
print("-----------------------")